### ISSUE TITLE
Re: 'Troubleshooting GovWifi in your organisation - GovWifi'

### ISSUE THREAD

**Issue by AnthonyWalpole** [alphagov/govwifi-tech-docs#188]
I have repeatedly tried to set up two external auditors from the European Commission on GovWiFi. They are conducting a review of our work in the Government Internal Audit Agency. I am trying to get access to them to GovWifi but the sponsor@wifi.service.gov.uk email address will not accept them.

The two email address I'm trying to set up are 

Milan.KOVACS@ec.europa.eu 

laszlo.polgar@ec.europa.eu

**Comment by leonaAtkins** [comment]
I'm sorry to hear of these issues registering emails with govwifi, please can you contact your orgs network admin to raise a ticket via our official support channels, that way this can be investigated, if you are an admin, the link to raise a support ticket is in the admin app, thank you.
