### ISSUE TITLE
Re: 'Offer GovWifi in your public sector organisation'

### ISSUE THREAD

**Issue by morgan37372** [alphagov/govwifi-tech-docs#203]
Problem with 'Offer GovWifi in your public sector organisation' (docs.wifi.service.gov.uk/)

Gov wifi in raf cosford cheshire 8D, does not connect fully to mobile devices

**Comment by leonaAtkins** [comment]
**Please Note:** this is *not* a support channel, if you are experiencing problems with GovWifi please contact your Network Administrators who can raise a ticket with us via the Admin Portal. thank you.
