### ISSUE TITLE
Re: 'Troubleshooting GovWifi in your organisation - GovWifi'

### ISSUE THREAD

**Issue by l-johns** [alphagov/govwifi-tech-docs#210]
Problem with 'Troubleshooting GovWifi in your organisation - GovWifi' (docs.wifi.service.gov.uk/troubleshooting.html)

Unable to access the following page:
https://www.wifi.service.gov.uk/connect-to-govwifi/get-help-connecting/

404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL as well as any file permissions.
For root URLs (like http://example.com/) you must provide an index.html file.

**Comment by leonaAtkins** [comment]
Thank you, link corrected.
