### ISSUE TITLE
OUTAGE HMS DRAKE HMS DEVONPORT 28th this morning

### ISSUE THREAD

**Issue by keithvarcoe** [alphagov/govwifi-tech-docs#212]
hi
can you give brief details of the GOV wifi outage experienced  at HMS Drake HMNB Devonport today (28th Nov) that was resolved about 09:00
regards

**Comment by leonaAtkins** [comment]
**Please Note:** this is *not* a support channel, if you are experiencing problems with GovWifi please contact your Network Administrators who can raise a ticket with us via the Admin Portal. thank you.
