### ISSUE TITLE
GovWifi - Defence Medical Services, Whittington Barracks, WS14 9PY

### ISSUE THREAD

**Issue by tjp831** [alphagov/govwifi-tech-docs#224]
Problem with 'Manage GovWifi in your organisation - GovWifi' (docs.wifi.service.gov.uk/manage.html)

Good morning,

I am the IT Services Manager for Defence Medical Services, Whittington Barracks, WS14 9PY. We have had GOV WiFi on site for a number of years but there isn't any information held on who arranged for it to be set up and who is the point of contact to manage any problems.

Two weeks ago the GOV WiFi stopped working in our office buildings. I am led to believe GOV WiFi piggy backs onto our DBI system which is running normal. I reported that GOV WiFi is down to the DBI Helpdesk who arranged for a BT engineer to attend site, he has been this week and informed me that their equipment is working fine.

Neither the engineer or the DBI helpdesk have been able to provide me with guidance on the way forward to restore GOV WiFi on site.

Can you provide me with details on how I report the issue please.

Many thanks,

Terry Powell (01543 434128)

**Comment by leonaAtkins** [comment]
**Please Note:** this is *not* a support channel, if you are still experiencing problems with GovWifi please contact your Network Administrators who can raise a ticket with us via the Admin Portal. thank you.
