### ISSUE TITLE
Re: 'Troubleshooting GovWifi in your organisation - GovWifi'

### ISSUE THREAD

**Issue by Sapphican** [alphagov/govwifi-tech-docs#226]
Problem with 'Troubleshooting GovWifi in your organisation - GovWifi' (docs.wifi.service.gov.uk/troubleshooting.html)

The GOV WiFi in the RAF Marham area cannot be connected to by any of my devices. It was working perfectly yesterday (22/03/24) and all of today until 1730 where what seemed like a power cut has completely cut off the internet connection.

The Status page on the Gov website says there are no incidents but I would like to raise this and attempt to have it fixed

**Comment by leonaAtkins** [comment]
**Please Note:** this is *not* a support channel, if you are experiencing problems with GovWifi please contact your Network Administrators who can raise a ticket with us via the Admin Portal. thank you.
