### ISSUE TITLE
No GovWifi in our organisation - GovWifi'

### ISSUE THREAD

**Issue by HathPMWendy** [alphagov/govwifi-tech-docs#236]
Problem with 'Troubleshooting GovWifi in your organisation - GovWifi' (docs.wifi.service.gov.uk/troubleshooting.html)
Hathaway medical centre cannot access Govwifi - this has been down now for over an hour

**Comment by leonaAtkins** [comment]
I'm sorry to hear you can't get govwifi, please can you contact your orgs network admin to raise a ticket via our official support channels, that way this can be investigated, if you are an admin, the link to raise a support ticket is in the admin app,  thank you.
